### ISSUE TITLE
Output clipping in training mode

### ISSUE THREAD

**Issue by jopetty** [clay-lab/transductions#15]
think I figured out what was causing the error that was preventing everything from running until this weekend. If we look in `models.py`, inside the `forward()` method of `DecoderRNN`, it seems that when in training mode there is a check to make sure that the model never outputs a sequence longer than the target and the output is clipped to this length, while in eval mode the output is clipped to the value of `max_length`, in this case 30. This makes sense, I think, but it does mess up our eval code since the `target` and `output` are tensors of `size sequence_length x batch_size x (vocab)` and the criterion doesn’t like it when the 0th dimension of the tensors don’t match. @bobfrank1  I recall you saying something during out last call about how this ordering of the tensor dimensions was conventional, but could be changed. Would swapping one of these fix the issue without resorting to the “clipping” hack I’ve currently implemented? Or, if not, what is the usual way that variable sequence length is dealt with for RNNs?

**Comment by bobfrank1** [comment]
Right -- when we are doing teacher forcing the idea is that we are giving the network the correct next step, which means that it would never generate past the target length (at which point, it would get an <eos> token, presumably).  If we want the result of forward to produce something with a uniformly sized first dimension (set to `max_length`), we could just change the last line of forward to return `outputs`, rather than `outputs[:gen_length]`. This tensor is initialized to have a first dimension of size `max_length`, so it should always be of that size, I think.
